#include "battery_icons.h"
#include "home_icons.h"
#include "music_icons.h"
#include "note_icons.h"
#include "game_icons.h"
#include "facebook_icons.h"
#include "image_icons.h"
#include "back_icon.h"
